import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Product from '../../components/Product';
import Categories from '../../components/Categories';
import MainLayout from '../../layouts/main.layout';

async function getProducts() {
  // fetch data from an API
  const url = 'https://lfs-api.onrender.com/api/products?populate=*';
  const res = await fetch(url, { cache: 'no-store' });
  //const res = await fetch(url, { next: { revalidate: 60 } });
  const products = await res.json();
  //console.log(data)
  // sort by category and code
  const sortedData = products.data.sort((a: any, b: any) => {
    if (a.attributes.category.data.attributes.name < b.attributes.category.data.attributes.name) {
      return -1
    }
    if (a.attributes.category.data.attributes.name > b.attributes.category.data.attributes.name) {
      return 1
    }
    if (a.attributes.code < b.attributes.code) {
      return -1
    }
    if (a.attributes.code > b.attributes.code) {
      return 1
    }
    return 0
  })

  return products.data;
}

export async function getServerSideProps() {
  const products = await getProducts();
  return { props: { products: products } };
}


const ProducsPage = ({ products }: { products: any }) => {

  return (
    <MainLayout>
      <div className="grid place-items-center min-h-screen bg-gray-50 p-8">
      <Head>
        <title>NextJS-SWA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul className="p-4 max-w-6xl grid gap-4 sm:grid-cols-2 md:grid-cols-3">
        <li className="text-4xl text-red-700 font-noticia font-extrabold sm:col-span-2 sm:grid sm:grid-cols-2 gap-4 md:grid-cols-3 md:col-span-3">
          <h1 className='md:col-span-2'>
            <span className='italic text-yellow-600'>All Products</span>
          </h1>
        </li>
        <li className='md:block uppercase'>
          <Categories />
        </li>
        <li className='italic text-blue-600 hidden md:block sm:row-start-2 sm:col-start-2 sm:self-center md:col-start-2 md:col-span-2 border-2 rounded-xl border-red-500 border-dotted p-4'>
          <p className='text-xl'>
          Welcome to L & FS Global Trading, the premier destination for exquisite traditional Vietnamese products and ingredients.
          With a decade of experience as a trusted importer, we take pride in supplying our loyal and new customers 
          with the most pristine products that bring the authentic taste of Vietnam right to your place of business. 
          Our commitment to excellence ensures that our customers receive the highest quality products and the best service possible.
          <br /><br />
          You can find our amazing range of products gracing the shelves of Asian Supermarkets all across Australia, 
          a testament to our dedication and reputation in the industry.
          <br /><br />
          Whether you are a new customer or returning enthusiast, we are always delighted to assist you with our extensive product selection. 
          Reach out to us today and let us help you, while you help us continue to provide these exceptional Vietnamese delicacies. 

          </p>
        </li>
          {products.map((product:any) => {
            return (
              <Product key={product.id} product={product} />
            )
          })}
      </ul>
    </div>
    </MainLayout>    
  )
}

export default ProducsPage
